#!/usr/bin/env bash
# script that configure our ubuntu server to respect our arguments.
#look for output  in the nginx /var/www/html/index.nginx-debian.html
#check if nginx is listening to a port

sudo apt-get -y update
sudo apt-get -y install nginx

# Check if Nginx is listening on port 80
sudo ss -lnpt | grep ':80'

echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start

# Check if the index file contains the expected message
cat /var/www/html/index.nginx-debian.html


sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index
sudo sed -i 's/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/f permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
