#!/usr/bin/env bash
# Installs Nginx with the following configurations:
## server
## Nginx should be listening on port 80
## When querying Nginx at its root / with a GET request (requesting a page)\
### using curl, it must return a page that contains the string Hello World!
## As an answer file, write a Bash script that configures a new Ubuntu machine\
### to respect above requirements (this script will be run on the server itself)
## You can’t use systemctl for restarting nginx

#apt-get -y update
#apt-get -y install nginx

#touch /var/www/html/index.html
#echo "Hello World!" > /var/www/html/index.html

#printf %s "server {
#    listen		80 default_server;
#    listen		[::]:80 default_server;
#    root		/var/www/html;
#    index		index.html index.htm index.nginx-debian.html;
#    location /redirect_me {
#        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
#    }
#}
#" > /etc/nginx/sites-available/default

#service nginx restart

#NEW CODE
sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
